version: "3.9"

services:
  mysql:
    image: yobasystems/alpine-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: bismillah
      MYSQL_DATABASE: twilux
      MYSQL_USER: roni
      MYSQL_PASSWORD: bismillah
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - /data/example/mysql:/var/lib/mysql
    restart: always
  api:
    image: niroin/twilux:1.0.2
    expose:
      - "80"
    ports:
      - "80:80"
    links:
      - mysql
    depends_on:
      - mysql
